### ISSUE TITLE
df.entities.xml:entity_event. Should union->derived type?

### ISSUE THREAD

**Issue by PatrikLundell** [DFHack/df-structures#225]
Is the union description where the various interpretations of the first 16 bytes a representation of the info that could be better represented as an overall type and derived types (in a similar way as the one used for interactions)?

**Comment by PatrikLundell** [comment]
It's a bit of work to set up padding, but I don't see any problem apart from that, but I may fail to see the issues. There are high level languages that can do that with ease (I'm not sure if XML's "choice" can handle it, but I think it can. Obviously, that means nothing if the XML -> C++ translation isn't present. After all, XML's "sequence" isn't used for vectors either).

**Comment by lethosor** [comment]
Not sure what you're referring to by "choice" - we have our own XML schema that directly translates into C++ headers.
Since this isn't a virtual class, we don't have any way to detect/convert it to subtypes automatically (like viewscreens in Lua), so every user would have to cast it by hand, which is tedious and would require checking the "type" field by hand anyway.

**Comment by PatrikLundell** [comment]
Choice and Sequence are two XML Schema structure features. A Choice maps very well to Ada's Variant Record, which in C(++) terms would be a Union with the added functionality that one or more specified fields determine which variant (i.e. set of fields) is to be used. In Ada an exception is thrown if you try to access a field which doesn't exist for the variant at hand (as it also does if you try to access an array out of bounds).
However, all of that is a tangent.

If it can't be converted into a virtual class with a reasonable effort I agree there's probably no good way to go about it, as the whole purpose of the exercise would be automatic subtype detection/conversion.

**Comment by lethosor** [comment]
Ah, that makes sense, I think. I'm not sure that it would be applicable to us, though - we want something in XML that can be used to easily generate a union in C++, not a union in XML itself.

Determining which part of a union is valid is something we don't have support for yet. @ragundo was working on a big protobuf project that involved exporting some unions, and I'm not sure if he figured out a good way to handle them. In general, it's the field before the union that determines the union type, but this case is different, and in general, neither our XML nor code generation supports determining subtypes based on arbitrary fields (or even expressions).

A bit of an aside, but it's possible that some small unions aren't really unions in DF - Toady could be using the same field for two completely different purposes, and someone decided to give them two different names in DFHack to better reflect that. I'm not sure if that's the case here or not, though.

**Comment by ragundo** [comment]
Yes
I faced that problem and there's no solution.
Becasue I was generating protocol buffers files, I just set each field of the union with a protobuf "optional" field and generate a method that can retrieve that field on the client side.
It's up to the client to decide which method to call on the dfhack side because there's no way to know the field that selects the correct union field
