### ISSUE TITLE
More globals (low-hanging fruit)

### ISSUE THREAD

**Issue by Bumber64** [DFHack/df-structures#446]
There are some unmapped global variables that are named in DF's data segment. For example:
```
.data:00000001410B6620 dq offset aDebugAlwayshap               ; "DEBUG_ALWAYSHAPPY"
.data:00000001410B6628 dq offset unk_141697472
.data:00000001410B6630 dq offset aDebugNeverbers               ; "DEBUG_NEVERBERSERK"
.data:00000001410B6638 dq offset _debug_noberserk
.data:00000001410B6640 dq offset aDebugDisablehu               ; "DEBUG_DISABLEHUMANCARAVAN"
.data:00000001410B6648 dq offset unk_14167E41F
.data:00000001410B6650 dq offset aDebugGamelog                 ; "DEBUG_GAMELOG"
.data:00000001410B6658 dq offset byte_1410B67E0
```
(DF 0.47.05, Windows 64-bit)
I know from reverse-engineering that ``debug_gamelog`` prevents writing to gamelog.txt when false.
``debug_alwayshappy`` and ``debug_disablehumancaravan`` seem self explanatory. There are a bunch of other variables in this area.

**Comment by quietust** [comment]
DEBUG_GAMELOG has been present since at least 0.44.01, possibly earlier. It definitely was _not_ present back in 40d.

However, "ALWAYSHAPPY" was obsoleted back when Stress was added and currently does nothing at all, and all of the others (SHOW_RIVER, FASTCAVEIN, and DISABLEHUMANCARAVAN) only existed in version 0.23.130.23a and earlier.
