### ISSUE TITLE
Offsets issues in 0.50

### ISSUE THREAD

**Issue by cvuchener** [DFHack/df-structures#505]
Here are the issues I found when testing Dwarf Therapist.

- [x] `material` is misaligned, it requires removing the new anonymous `int32_t` at the end of `material_common` fixes it. But `material_template` requires different changes (see #497)
- [x] `itemdef` has a new 64 bits field at the end. I don't what it is, it is always 0. I know it is part of `itemdef` and not the derived classes because I checked the constructor.
- [x] `unit.inventory` needs to be 8 bytes before. `unit.riding_item_id` is gone but `unit.job` seems correct, so it may have moved before `unit.job` or there is a new field there.
- [x] `ui.main.fortress_entity` is gone and I don't see anything looking like a valid pointer around its supposed location.

**Comment by ab9rf** [comment]
* `material`. `material_template` and `material_common` are all corrected in 829f9b36920f45295d42f097cdb6ccad9e7d9085 (on quietust's fork, not yet merged to master)
* `unitst.inventory` is corrected in 045a3f1bd94b8e7f23e47783c135fd0bf3c6e216 (pending PR #499, not yet merged)
* `fortress_entity` and `fortress_site` moved significantly but are still there; see 829f9b36920f45295d42f097cdb6ccad9e7d9085

`itemdefst` is indeed 8 bytes longer now, although the use of the additional 8 bits is unclear. there is nothing helpful in the destructor. it's impossible to tell what might be there from the constructor because of MSVC write combining, destructors are far more useful. i've checked a handful of subtypes and they're also off (for example, `itemdef_armorst` is 0x110 in structures but actually 0x170 so there's more than just the added 8 bytes involved there. obviously all the itemdef classes need to be checked, which i don't think anyone has done yet

**Comment by ab9rf** [comment]
- [ ] itemdefst (0x60 -> 0x68)
- [ ] item_ammost (0xf0 -> 0x170)
- [ ] item_armorst (0xe8 -> 0x168)
- [ ] item_foodst (0xf8 -> 0x98)
- [ ] item_glovest (0xf8 -> 0x128)
- [ ] item_helmst (0xe8 -> 0x128)
- [ ] item_instrumentst (0xe8 -> 0x298)
- [ ] item_pantsst (0xe8 -> 0x168)
- [ ] item_shieldst (0xe8 -> 0xf8)
- [ ] item_shoesst (0xe8 -> 0x128)
- [ ] item_siegeammost (0xf0 -> 0x120)
- [ ] item_toolst (0x100 -> 0x330)
- [ ] item_toyst (0xe8 -> 0xe8)
- [ ] item_trapcompst (0xf0 -> 0x170)
- [ ] item_weaponst (0xf0 -> 0x1b8)
