### ISSUE TITLE
Identified some of markup_text_boxst

### ISSUE THREAD

**Issue by alattalatta** [DFHack/df-structures#574]
I'm no reverse engineer but I was able to figure out what these do by evaluating lua scripts. (Steam 50.07)

## markup_text_boxst.unk1 

Is a vector of words. Line breaks are also words of its own, but not spaces. Each word can have a *hyperlink*. (See `markup_text_boxst.unk_v50_2`)

- `unk_00`: The word, string.
- `unk_24`: Index of `markup_text_boxst.unk_v50_2` vector. This is for hyperlinking. `-1` for none, i.e. plain text.
- `unk_28`: Position of the word along the X axis. `-1` for line breaks.
- `unk_2c`: Position of the word along the Y axis. `-1` for line breaks.
- ~~`unk_30`~~

So for a sentence "Serid Skincrafts was a anaconda.", `markup_text_boxst.unk1[1]` would be

```
unk_00: "Skincrafts"
unk_24: -1
unk_28: 6
unk_2c: 0
```

## markup_text_boxst.unk_v50_2

Is a vector of hyperlinks.

- `unk_0`: Type of target. See #569.
- `unk_4`: ID of target.
- ~~`unk_8`: Always -1?~~

For historical figures, I can:

```lua
local id = markup_text_boxst.unk_v50_2[index].unk_4
return df.historical_figure.find(id)
```

to retrieve the figure this hyperlink points.

## markup_text_boxst.unk_v50_3

`markup_text_boxst`'s width.

## markup_text_boxst.unk_v50_4

`markup_text_boxst`'s height.

**Comment by Bumber64** [comment]
Just stumbled across this after preparing some changes to the variable names, since I've finished cleaning up the whole reverse engineered function to something readable. This let me confirm that `unk_24` is an index in `unk_v50_2`.

On [my df-structures branch](https://github.com/Bumber64/df-structures/tree/patch-1), I went and renamed these variables:
`unk1` -> `hypertext` (This is the vector containing the hyperlink entries. I think it might be the name of the struct type, too?)
`unk_00` -> `text` (Could probably also call this `word_text`, `word_string`, etc.)
`unk_24` -> `lpage_ref_index` (See `lpage_ref` struct below.)
`unk_30` -> `mtb_flags` (Could call this `hypertext_flags`. Flag `B` is set whenever `text` is empty, probably indicates line break?)

I didn't rename `unk_28` or `unk_2c` because they aren't handled in the function. It may be reasonable to call them `text_pos_x` and `text_pos_y` based on observation. Likewise, `unk_v50_3` and `unk_v50_4` can be `box_width` and `box_height`. `world.status.unk_v50_1` could be renamed to `world.status.active_text_box`.

I renamed `unk_v50_2` to `lpage_refs` and created a struct `lpage_ref` for it in `df.refs.xml` like this:
```
<enum-type type-name='lpage_ref_type'>
    <enum-item name='NONE' value='-1'/>
    <enum-item name="HF"/>
    <enum-item name="SITE"/>
    <enum-item name="ARTIFACT"/>
    <enum-item name="BOOK"/>
    <enum-item name="SR"/> SUBREGION?
    <enum-item name="FL"/> FEATURE_LAYER?
    <enum-item name="ENT"/> ENTITY?
    <enum-item name="AB"/> ABSTRACT_BUILDING?
    <enum-item name="EPOP"/> ENTITY_POP?
    <enum-item name="ART_IMAGE"/>
    <enum-item name="ERA"/>
    <enum-item name="HEC"/>
</enum-type>

<struct-type type-name='lpage_ref'>
    <enum name='type' base-type='int32_t' type-name='lpage_ref_type'/>
    <int32_t name='ref1' init-value='-1'/>
    <int32_t name='ref2' init-value='-1'/> only used when type is AB or ART_IMAGE
</struct-type>
```
Therefore `unk_0`, `unk_4`, and `unk_8` are renamed `type`, `ref1`, and `ref2`, respectively. The term `lpage` comes from the reverse engineered function, which parses something like `[LPAGE:HF:1]hyperlink text[/LPAGE]` to create the ref. The 'L' might stand for "legends", depending upon what's supposed to happen when you click on the link.

**Comment by Bumber64** [comment]
Does something happen when you click on a hyperlink? In your example, "Skincrafts" is just plain text with an index of -1, so you might have to manually create an entry in the vector to index to (unless "Serid" has the hyperlink.)

If that opens a page with info about the HF, then we might also test the other ref types by putting in arbitrary ref numbers for those.

Are there restrictions on when these hyperlinks work, e.g., worldgen but not dwarf mode popups?

**Comment by Bumber64** [comment]
I think this can be marked closed now?
